version: "3.8"

services:
  # FreePeak DB MCP Server - Development Environment
  db-mcp-server-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-db-mcp
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TRANSPORT_MODE: stdio
      CONFIG_PATH: /app/config.json
      ENVIRONMENT: development
    env_file:
      - .env
    ports:
      - "9092:9092"
    networks:
      - mcp-dev-network

networks:
  mcp-dev-network:
    driver: bridge
